"""Cell → pickle mapping for TAPTN ICL tables.

`src` is an absolute path on the author machine (used only when assembling the
asset bundle). `dest` is relative to TAPTN_ASSETS. `method` selects the scorer.
"""
from __future__ import annotations

HOME = "/home/wanghongyi/LLM-Structured-Data-main"
DATA1 = "/data1/wanghongyi/LLM_Graph_Structural_Info/LLM-Structured-Data-main"

# method:
#   wrong_index  1 - |wrong|/|result|
#   stored       pkl['accuracy']  (fraction)
#   acc_gate     pkl['acc_gate']  (already percent)
#   reextract    pkl['accuracy_reextract']
#   product_400  hop1 wrong_index as positions ∩ 400 test keys of extra
#   dense_json   dense_results.json summary.accuracy
#   cost_json    cost_probe JSON (handled separately)
#   missing      no artifact

def C(table, key, paper, dest, src, method, extra=None, note=None):
    return dict(table=table, key=key, paper=paper, dest=dest, src=src,
                method=method, extra=extra, note=note)


CELLS = [
    # ── tab:main_5_datasets ──────────────────────────────────────────────
    C("tab:main_5_datasets", "0hop.cora", 59.40, None, None, "missing",
      note="No 0-hop GPT-3.5 Cora pickle; closest DATA1 ego runs are 63.65 / 52.40."),
    C("tab:main_5_datasets", "0hop.arxiv_2023", 76.19,
      "pkls/main/arxiv2023_ego.pkl", f"{HOME}/arxiv2023_ego.pkl", "wrong_index"),
    C("tab:main_5_datasets", "0hop.texas", 66.93, None, None, "missing",
      note="Closest file texas_ego_noguide.pkl is 66.80 (171/256)."),
    C("tab:main_5_datasets", "0hop.wisconsin", 68.85,
      "pkls/main/wisconin2_ego_noguide.pkl", f"{HOME}/wisconin2_ego_noguide.pkl",
      "wrong_index", note="Filename misspells Wisconsin as wisconin."),
    C("tab:main_5_datasets", "0hop.cornell", 72.58,
      "pkls/main/cornell2_ego_noguide.pkl", f"{HOME}/cornell2_ego_noguide.pkl", "wrong_index"),

    C("tab:main_5_datasets", "gicl1.cora", 62.55, None, None, "missing",
      note="Hardcoded in generate_tables.py; cora_hop2_anon_noguide is a different cell (decouple 2-hop, no SAT)."),
    C("tab:main_5_datasets", "gicl1.arxiv_2023", 83.49,
      "pkls/main/arxiv2023_hop1_noguide2.pkl", f"{HOME}/arxiv2023_hop1_noguide2.pkl", "wrong_index"),
    C("tab:main_5_datasets", "gicl1.texas", 65.23,
      "pkls/main/texas2_hop1_noguide_test.pkl", f"{HOME}/texas2_hop1_noguide_test.pkl", "wrong_index"),
    C("tab:main_5_datasets", "gicl1.wisconsin", 76.01,
      "pkls/main/wisconsin2_hop1_noguide_test.pkl", f"{HOME}/wisconsin2_hop1_noguide_test.pkl", "wrong_index"),
    C("tab:main_5_datasets", "gicl1.cornell", 76.21,
      "pkls/main/cornell2_hop1_noguide_test.pkl", f"{HOME}/cornell2_hop1_noguide_test.pkl", "wrong_index"),

    C("tab:main_5_datasets", "gicl2.cora", 63.47, None, None, "missing",
      note="main.py comment: original setting 63.47% if abstracts are not used; pickle not found."),
    C("tab:main_5_datasets", "gicl2.arxiv_2023", 85.40,
      "pkls/main/arxiv2023_hop2_noguide.pkl", f"{HOME}/arxiv2023_hop2_noguide.pkl", "wrong_index"),
    C("tab:main_5_datasets", "gicl2.texas", 66.41,
      "pkls/main/texas2_hop2_noguide_test.pkl", f"{HOME}/texas2_hop2_noguide_test.pkl", "wrong_index"),
    C("tab:main_5_datasets", "gicl2.wisconsin", 70.72,
      "pkls/main/wisconsin2_hop2_noguide_test.pkl", f"{HOME}/wisconsin2_hop2_noguide_test.pkl", "wrong_index"),
    C("tab:main_5_datasets", "gicl2.cornell", 72.18,
      "pkls/main/cornell2_hop2_noguide.pkl", f"{HOME}/cornell2_hop2_noguide.pkl", "wrong_index"),

    C("tab:main_5_datasets", "taptn1.cora", 72.69, None, None, "missing",
      note="Hardcoded; Llama file cora_hop1_iter2_neighbors_refine_llama_3.3_70b_i.pkl is 72.69 but wrong backbone."),
    C("tab:main_5_datasets", "taptn1.arxiv_2023", 87.30,
      "pkls/main/arxiv2023_hop1_guide.pkl", f"{HOME}/arxiv2023_hop1_guide.pkl", "wrong_index"),
    C("tab:main_5_datasets", "taptn1.texas", 89.84,
      "pkls/main/texas2_hop1_guide_test.pkl", f"{HOME}/texas2_hop1_guide_test.pkl", "wrong_index"),
    C("tab:main_5_datasets", "taptn1.wisconsin", 85.67,
      "pkls/main/wisconsin2_hop1_guide_test.pkl", f"{HOME}/wisconsin2_hop1_guide_test.pkl", "wrong_index"),
    C("tab:main_5_datasets", "taptn1.cornell", 85.08, None, None, "missing",
      note="Old cornell2_hop1_guide_test.pkl is 90.23 on n=256 (likely mislabelled). New noanon_guide Llama is 85.89."),

    C("tab:main_5_datasets", "taptn2.cora", 73.80,
      "pkls/main/cot_cora_refining35_test.pkl", f"{HOME}/cot_cora_refining35_test.pkl", "wrong_index"),
    C("tab:main_5_datasets", "taptn2.arxiv_2023", 88.57,
      "pkls/main/arxiv2023_hop1_guide_test_refine35.pkl",
      f"{HOME}/arxiv2023_hop1_guide_test_refine35.pkl", "wrong_index"),
    C("tab:main_5_datasets", "taptn2.texas", 91.80,
      "pkls/main/texas2_hop1_guide_2.pkl", f"{HOME}/texas2_hop1_guide_2.pkl", "wrong_index"),
    C("tab:main_5_datasets", "taptn2.wisconsin", 87.23,
      "pkls/main/wisconsin2_hop1_guide_2.pkl", f"{HOME}/wisconsin2_hop1_guide_2.pkl", "wrong_index"),
    C("tab:main_5_datasets", "taptn2.cornell", 86.69,
      "pkls/main/cornell2_hop1_guide_2.pkl", f"{HOME}/cornell2_hop1_guide_2.pkl", "wrong_index"),

    # ── tab:factorial  (gicl/taptn rows alias main gicl2/taptn2) ─────────
    C("tab:factorial", "gicl.cora", 63.47, None, None, "missing",
      note="Same missing Cora GraphICL 2-hop pickle as the main table."),
    C("tab:factorial", "gicl.arxiv_2023", 85.40,
      "pkls/main/arxiv2023_hop2_noguide.pkl", f"{HOME}/arxiv2023_hop2_noguide.pkl", "wrong_index"),
    C("tab:factorial", "gicl.texas", 66.41,
      "pkls/main/texas2_hop2_noguide_test.pkl", f"{HOME}/texas2_hop2_noguide_test.pkl", "wrong_index"),
    C("tab:factorial", "gicl.wisconsin", 70.72,
      "pkls/main/wisconsin2_hop2_noguide_test.pkl", f"{HOME}/wisconsin2_hop2_noguide_test.pkl", "wrong_index"),
    C("tab:factorial", "gicl.cornell", 72.18,
      "pkls/main/cornell2_hop2_noguide.pkl", f"{HOME}/cornell2_hop2_noguide.pkl", "wrong_index"),

    C("tab:factorial", "instr.cora", 73.25,
      "pkls/factorial/cora_hop2_noanon_guide_gpt-3.5-turbo-0125.pkl",
      f"{HOME}/cora_hop2_noanon_guide_gpt-3.5-turbo-0125.pkl", "stored"),
    C("tab:factorial", "instr.arxiv_2023", 86.03,
      "pkls/factorial/arxiv_2023_hop2_noanon_guide_gpt-3.5-turbo-0125.pkl",
      f"{HOME}/arxiv_2023_hop2_noanon_guide_gpt-3.5-turbo-0125.pkl", "stored"),
    C("tab:factorial", "instr.texas", 86.72,
      "pkls/factorial/texas_hop2_noanon_guide_llama-3.3-70b-instruct.pkl",
      f"{HOME}/texas_hop2_noanon_guide_llama-3.3-70b-instruct.pkl", "stored"),
    C("tab:factorial", "instr.wisconsin", 83.18,
      "pkls/factorial/wisconsin_hop2_noanon_guide_llama-3.3-70b-instruct.pkl",
      f"{HOME}/wisconsin_hop2_noanon_guide_llama-3.3-70b-instruct.pkl", "stored"),
    C("tab:factorial", "instr.cornell", 81.45,
      "pkls/factorial/cornell_hop2_noanon_guide_llama-3.3-70b-instruct.pkl",
      f"{HOME}/cornell_hop2_noanon_guide_llama-3.3-70b-instruct.pkl", "stored"),

    C("tab:factorial", "aggr.cora", 70.85,
      "pkls/factorial/cora_hop1_iter1_neighbors_gpt_3.5_turbo_0.pkl",
      f"{DATA1}/cora_hop1_iter1_neighbors_gpt_3.5_turbo_0.pkl", "wrong_index"),
    C("tab:factorial", "aggr.arxiv_2023", 87.30,
      "pkls/factorial/arxiv2023_hop1_noguide_refine2.pkl",
      f"{HOME}/arxiv2023_hop1_noguide_refine2.pkl", "wrong_index",
      note="Home arxiv2023_hop1_noguide_refine.pkl is a later 81.27 run; paper uses refine2 / DATA1 refine = 87.30."),
    C("tab:factorial", "aggr.texas", 66.79,
      "pkls/factorial/texas2_hop1_noguide_2.pkl", f"{HOME}/texas2_hop1_noguide_2.pkl",
      "wrong_index", note="171/256 = 66.80; paper typesets 66.79."),
    C("tab:factorial", "aggr.wisconsin", 73.21,
      "pkls/factorial/wisconsin2_hop1_noguide_2.pkl", f"{HOME}/wisconsin2_hop1_noguide_2.pkl", "wrong_index"),
    C("tab:factorial", "aggr.cornell", 77.82,
      "pkls/factorial/cornell2_hop1_noguide_2.pkl", f"{HOME}/cornell2_hop1_noguide_2.pkl", "wrong_index"),

    C("tab:factorial", "taptn.cora", 73.80,
      "pkls/main/cot_cora_refining35_test.pkl", f"{HOME}/cot_cora_refining35_test.pkl", "wrong_index"),
    C("tab:factorial", "taptn.arxiv_2023", 88.57,
      "pkls/main/arxiv2023_hop1_guide_test_refine35.pkl",
      f"{HOME}/arxiv2023_hop1_guide_test_refine35.pkl", "wrong_index"),
    C("tab:factorial", "taptn.texas", 91.80,
      "pkls/main/texas2_hop1_guide_2.pkl", f"{HOME}/texas2_hop1_guide_2.pkl", "wrong_index"),
    C("tab:factorial", "taptn.wisconsin", 87.23,
      "pkls/main/wisconsin2_hop1_guide_2.pkl", f"{HOME}/wisconsin2_hop1_guide_2.pkl", "wrong_index"),
    C("tab:factorial", "taptn.cornell", 86.69,
      "pkls/main/cornell2_hop1_guide_2.pkl", f"{HOME}/cornell2_hop1_guide_2.pkl", "wrong_index"),

    # ── tab:product_70b ──────────────────────────────────────────────────
    C("tab:product_70b", "gicl2", 76.50,
      "pkls/product/product_hop2_noanon_noguide_llama-3.3-70b-instruct.pkl",
      f"{HOME}/product_hop2_noanon_noguide_llama-3.3-70b-instruct.pkl", "stored"),
    C("tab:product_70b", "dense", 76.75,
      "cost_probe/dense_graphicl/dense_results.json",
      f"{HOME}/cost_probe/dense_graphicl/dense_results.json", "dense_json",
      note="307/400 on the same 400 test ids; not amazon_hop1_guide24.pkl (tb_52)."),
    C("tab:product_70b", "taptn1", 83.75,
      "pkls/product/product_hop1_noanon_guide_llama-3.3-70b-instruct_2.pkl",
      f"{HOME}/product_hop1_noanon_guide_llama-3.3-70b-instruct_2.pkl",
      "product_400",
      extra="pkls/product/product_hop1_noanon_guide_llama-3.3-70b-instruct_iter2_3.pkl",
      note="Global stored acc is 82.66% on 1430 nodes; paper 83.75 is the 400-node intersection."),
    C("tab:product_70b", "taptn2", 86.75,
      "pkls/product/product_hop1_noanon_guide_llama-3.3-70b-instruct_iter2_3.pkl",
      f"{HOME}/product_hop1_noanon_guide_llama-3.3-70b-instruct_iter2_3.pkl", "stored"),

    # ── tb_52 ────────────────────────────────────────────────────────────
    C("tb_52", "gicl.1.no", 74.75,
      "pkls/tb52/amazon_hop1_noguide_1.pkl", f"{HOME}/amazon_hop1_noguide_1.pkl", "wrong_index"),
    C("tb_52", "gicl.2.no", 75.00,
      "pkls/tb52/amazon_hop2_noguide.pkl", f"{HOME}/amazon_hop2_noguide.pkl", "wrong_index"),
    C("tb_52", "taptn.1.no", 74.75,
      "pkls/tb52/amazon_hop1_guide_12.pkl", f"{HOME}/amazon_hop1_guide_12.pkl", "wrong_index",
      note="Paper lists the same 74.75 for TAPTN 1-hop with and without instructions; only this file exists."),
    C("tb_52", "taptn.1.yes", 74.75,
      "pkls/tb52/amazon_hop1_guide_12.pkl", f"{HOME}/amazon_hop1_guide_12.pkl", "wrong_index"),
    C("tb_52", "taptn.2.no", 74.00,
      "pkls/tb52/amazon_hop1_noguide_2.pkl", f"{HOME}/amazon_hop1_noguide_2.pkl", "wrong_index"),
    C("tb_52", "taptn.2.yes", 76.75,
      "pkls/tb52/amazon_hop1_guide24.pkl", f"{HOME}/amazon_hop1_guide24.pkl", "wrong_index",
      note="Same 76.75 as dense GraphICL but a different artifact (mixed 8B/70B budget run)."),

    # ── tb_4 ─────────────────────────────────────────────────────────────
    C("tb_4", "gicl.1.0.cora", 62.55, None, None, "missing"),
    C("tb_4", "gicl.1.0.arxiv_2023", 83.49,
      "pkls/main/arxiv2023_hop1_noguide2.pkl", f"{HOME}/arxiv2023_hop1_noguide2.pkl", "wrong_index"),
    C("tb_4", "gicl.1.1.cora", 69.19, None, None, "missing"),
    C("tb_4", "gicl.1.1.arxiv_2023", 74.92,
      "pkls/reflect/arxiv2023_hop1_noguide_reflect.pkl",
      f"{HOME}/arxiv2023_hop1_noguide_reflect.pkl", "wrong_index"),
    C("tb_4", "gicl.1.2.cora", 68.45, None, None, "missing"),
    C("tb_4", "gicl.1.2.arxiv_2023", 73.65,
      "pkls/reflect/arxiv2023_hop1_noguide_reflect_double.pkl",
      f"{HOME}/arxiv2023_hop1_noguide_reflect_double.pkl", "wrong_index"),
    C("tb_4", "gicl.2.0.cora", 63.47, None, None, "missing"),
    C("tb_4", "gicl.2.0.arxiv_2023", 85.40,
      "pkls/main/arxiv2023_hop2_noguide.pkl", f"{HOME}/arxiv2023_hop2_noguide.pkl", "wrong_index"),
    C("tb_4", "gicl.2.1.cora", 69.18, None, None, "missing"),
    C("tb_4", "gicl.2.1.arxiv_2023", 75.87,
      "pkls/reflect/arxiv2023_hop2_noguide_reflect.pkl",
      f"{HOME}/arxiv2023_hop2_noguide_reflect.pkl", "wrong_index"),
    C("tb_4", "gicl.2.2.cora", 68.45, None, None, "missing"),
    C("tb_4", "gicl.2.2.arxiv_2023", 80.00,
      "pkls/reflect/arxiv2023_hop2_noguide_reflect_double.pkl",
      f"{HOME}/arxiv2023_hop2_noguide_reflect_double.pkl", "wrong_index"),
    C("tb_4", "taptn.1.cora", 72.69, None, None, "missing"),
    C("tb_4", "taptn.1.arxiv_2023", 87.30,
      "pkls/main/arxiv2023_hop1_guide.pkl", f"{HOME}/arxiv2023_hop1_guide.pkl", "wrong_index"),
    C("tb_4", "taptn.2.cora", 73.80,
      "pkls/main/cot_cora_refining35_test.pkl", f"{HOME}/cot_cora_refining35_test.pkl", "wrong_index"),
    C("tb_4", "taptn.2.arxiv_2023", 88.57,
      "pkls/main/arxiv2023_hop1_guide_test_refine35.pkl",
      f"{HOME}/arxiv2023_hop1_guide_test_refine35.pkl", "wrong_index"),

    # ── tab:decouple  woS_woI, woS_wI, wS_woI, wS_wI ──────────────────────
    C("tab:decouple", "cora.1.woS_woI", 69.37,
      "pkls/decouple/cora_hop1_anon_noguide_gpt-3.5-turbo-0125.pkl",
      f"{HOME}/cora_hop1_anon_noguide_gpt-3.5-turbo-0125.pkl", "stored"),
    C("tab:decouple", "cora.1.woS_wI", 71.40,
      "pkls/decouple/cora_hop1_anon_guide_gpt-3.5-turbo-0125.pkl",
      f"{HOME}/cora_hop1_anon_guide_gpt-3.5-turbo-0125.pkl", "stored"),
    C("tab:decouple", "cora.1.wS_woI", 62.55, None, None, "missing"),
    C("tab:decouple", "cora.1.wS_wI", 72.69, None, None, "missing"),
    C("tab:decouple", "cora.2.woS_woI", 62.55,
      "pkls/decouple/cora_hop2_anon_noguide_gpt-3.5-turbo-0125.pkl",
      f"{HOME}/cora_hop2_anon_noguide_gpt-3.5-turbo-0125.pkl", "stored"),
    C("tab:decouple", "cora.2.woS_wI", 72.14,
      "pkls/decouple/cora_hop2_anon_guide_gpt-3.5-turbo-0125.pkl",
      f"{HOME}/cora_hop2_anon_guide_gpt-3.5-turbo-0125.pkl", "stored"),
    C("tab:decouple", "cora.2.wS_woI", 63.47, None, None, "missing"),
    C("tab:decouple", "cora.2.wS_wI", 73.25,
      "pkls/factorial/cora_hop2_noanon_guide_gpt-3.5-turbo-0125.pkl",
      f"{HOME}/cora_hop2_noanon_guide_gpt-3.5-turbo-0125.pkl", "stored"),

    C("tab:decouple", "arxiv_2023.1.woS_woI", 81.59,
      "pkls/decouple/arxiv_2023_hop1_anon_noguide_gpt-3.5-turbo-0125.pkl",
      f"{HOME}/arxiv_2023_hop1_anon_noguide_gpt-3.5-turbo-0125.pkl", "stored"),
    C("tab:decouple", "arxiv_2023.1.woS_wI", 85.71,
      "pkls/decouple/arxiv_2023_hop1_anon_guide_gpt-3.5-turbo-0125.pkl",
      f"{HOME}/arxiv_2023_hop1_anon_guide_gpt-3.5-turbo-0125.pkl", "stored"),
    C("tab:decouple", "arxiv_2023.1.wS_woI", 83.49,
      "pkls/main/arxiv2023_hop1_noguide2.pkl", f"{HOME}/arxiv2023_hop1_noguide2.pkl", "wrong_index"),
    C("tab:decouple", "arxiv_2023.1.wS_wI", 87.30,
      "pkls/main/arxiv2023_hop1_guide.pkl", f"{HOME}/arxiv2023_hop1_guide.pkl", "wrong_index"),
    C("tab:decouple", "arxiv_2023.2.woS_woI", 82.54,
      "pkls/decouple/arxiv_2023_hop2_anon_noguide_gpt-3.5-turbo-0125.pkl",
      f"{HOME}/arxiv_2023_hop2_anon_noguide_gpt-3.5-turbo-0125.pkl", "stored"),
    C("tab:decouple", "arxiv_2023.2.woS_wI", 86.35,
      "pkls/decouple/arxiv_2023_hop2_anon_guide_gpt-3.5-turbo-0125.pkl",
      f"{HOME}/arxiv_2023_hop2_anon_guide_gpt-3.5-turbo-0125.pkl", "stored"),
    C("tab:decouple", "arxiv_2023.2.wS_woI", 85.40,
      "pkls/main/arxiv2023_hop2_noguide.pkl", f"{HOME}/arxiv2023_hop2_noguide.pkl", "wrong_index"),
    C("tab:decouple", "arxiv_2023.2.wS_wI", 86.03,
      "pkls/factorial/arxiv_2023_hop2_noanon_guide_gpt-3.5-turbo-0125.pkl",
      f"{HOME}/arxiv_2023_hop2_noanon_guide_gpt-3.5-turbo-0125.pkl", "stored"),

    C("tab:decouple", "texas.1.woS_woI", 45.31,
      "pkls/decouple/texas_hop1_anon_noguide_llama-3.3-70b-instruct.pkl",
      f"{HOME}/texas_hop1_anon_noguide_llama-3.3-70b-instruct.pkl", "stored"),
    C("tab:decouple", "texas.1.woS_wI", 78.52,
      "pkls/decouple/texas_hop1_anon_guide_llama-3.3-70b-instruct.pkl",
      f"{HOME}/texas_hop1_anon_guide_llama-3.3-70b-instruct.pkl", "stored"),
    C("tab:decouple", "texas.1.wS_woI", 65.23,
      "pkls/main/texas2_hop1_noguide_test.pkl", f"{HOME}/texas2_hop1_noguide_test.pkl", "wrong_index"),
    C("tab:decouple", "texas.1.wS_wI", 89.84,
      "pkls/main/texas2_hop1_guide_test.pkl", f"{HOME}/texas2_hop1_guide_test.pkl", "wrong_index"),
    C("tab:decouple", "texas.2.woS_woI", 57.03,
      "pkls/decouple/texas_hop2_anon_noguide_llama-3.3-70b-instruct.pkl",
      f"{HOME}/texas_hop2_anon_noguide_llama-3.3-70b-instruct.pkl", "stored"),
    C("tab:decouple", "texas.2.woS_wI", 73.44,
      "pkls/decouple/texas_hop2_anon_guide_llama-3.3-70b-instruct.pkl",
      f"{HOME}/texas_hop2_anon_guide_llama-3.3-70b-instruct.pkl", "stored"),
    C("tab:decouple", "texas.2.wS_woI", 66.41,
      "pkls/main/texas2_hop2_noguide_test.pkl", f"{HOME}/texas2_hop2_noguide_test.pkl", "wrong_index"),
    C("tab:decouple", "texas.2.wS_wI", 86.72,
      "pkls/factorial/texas_hop2_noanon_guide_llama-3.3-70b-instruct.pkl",
      f"{HOME}/texas_hop2_noanon_guide_llama-3.3-70b-instruct.pkl", "stored"),

    C("tab:decouple", "wisconsin.1.woS_woI", 55.45,
      "pkls/decouple/wisconsin_hop1_anon_noguide_llama-3.3-70b-instruct.pkl",
      f"{HOME}/wisconsin_hop1_anon_noguide_llama-3.3-70b-instruct.pkl", "stored"),
    C("tab:decouple", "wisconsin.1.woS_wI", 81.31,
      "pkls/decouple/wisconsin_hop1_anon_guide_llama-3.3-70b-instruct.pkl",
      f"{HOME}/wisconsin_hop1_anon_guide_llama-3.3-70b-instruct.pkl", "stored"),
    C("tab:decouple", "wisconsin.1.wS_woI", 76.01,
      "pkls/main/wisconsin2_hop1_noguide_test.pkl", f"{HOME}/wisconsin2_hop1_noguide_test.pkl", "wrong_index"),
    C("tab:decouple", "wisconsin.1.wS_wI", 85.67,
      "pkls/main/wisconsin2_hop1_guide_test.pkl", f"{HOME}/wisconsin2_hop1_guide_test.pkl", "wrong_index"),
    C("tab:decouple", "wisconsin.2.woS_woI", 60.75,
      "pkls/decouple/wisconsin_hop2_anon_noguide_llama-3.3-70b-instruct.pkl",
      f"{HOME}/wisconsin_hop2_anon_noguide_llama-3.3-70b-instruct.pkl", "stored"),
    C("tab:decouple", "wisconsin.2.woS_wI", 80.37,
      "pkls/decouple/wisconsin_hop2_anon_guide_llama-3.3-70b-instruct.pkl",
      f"{HOME}/wisconsin_hop2_anon_guide_llama-3.3-70b-instruct.pkl", "stored"),
    C("tab:decouple", "wisconsin.2.wS_woI", 70.72,
      "pkls/main/wisconsin2_hop2_noguide_test.pkl", f"{HOME}/wisconsin2_hop2_noguide_test.pkl", "wrong_index"),
    C("tab:decouple", "wisconsin.2.wS_wI", 83.18,
      "pkls/factorial/wisconsin_hop2_noanon_guide_llama-3.3-70b-instruct.pkl",
      f"{HOME}/wisconsin_hop2_noanon_guide_llama-3.3-70b-instruct.pkl", "stored"),

    C("tab:decouple", "cornell.1.woS_woI", 56.45,
      "pkls/decouple/cornell_hop1_anon_noguide_llama-3.3-70b-instruct.pkl",
      f"{HOME}/cornell_hop1_anon_noguide_llama-3.3-70b-instruct.pkl", "stored"),
    C("tab:decouple", "cornell.1.woS_wI", 76.61,
      "pkls/decouple/cornell_hop1_anon_guide_llama-3.3-70b-instruct.pkl",
      f"{HOME}/cornell_hop1_anon_guide_llama-3.3-70b-instruct.pkl", "stored"),
    C("tab:decouple", "cornell.1.wS_woI", 76.21,
      "pkls/main/cornell2_hop1_noguide_test.pkl", f"{HOME}/cornell2_hop1_noguide_test.pkl", "wrong_index"),
    C("tab:decouple", "cornell.1.wS_wI", 85.08, None, None, "missing"),
    C("tab:decouple", "cornell.2.woS_woI", 62.10,
      "pkls/decouple/cornell_hop2_anon_noguide_llama-3.3-70b-instruct.pkl",
      f"{HOME}/cornell_hop2_anon_noguide_llama-3.3-70b-instruct.pkl", "stored"),
    C("tab:decouple", "cornell.2.woS_wI", 76.61,
      "pkls/decouple/cornell_hop2_anon_guide_llama-3.3-70b-instruct.pkl",
      f"{HOME}/cornell_hop2_anon_guide_llama-3.3-70b-instruct.pkl", "stored"),
    C("tab:decouple", "cornell.2.wS_woI", 72.18,
      "pkls/main/cornell2_hop2_noguide.pkl", f"{HOME}/cornell2_hop2_noguide.pkl", "wrong_index"),
    C("tab:decouple", "cornell.2.wS_wI", 81.45,
      "pkls/factorial/cornell_hop2_noanon_guide_llama-3.3-70b-instruct.pkl",
      f"{HOME}/cornell_hop2_noanon_guide_llama-3.3-70b-instruct.pkl", "stored"),

    # ── tab:current_channel (Texas) ──────────────────────────────────────
    C("tab:current_channel", "llama.ego", 66.80,
      "pkls/current_channel/texas_ego_noguide.pkl", f"{HOME}/texas_ego_noguide.pkl", "wrong_index"),
    C("tab:current_channel", "llama.anon", 45.31,
      "pkls/current_channel/texas_hop1_anon_noguide_llama-3.3-70b-instruct.pkl",
      f"{HOME}/texas_hop1_anon_noguide_llama-3.3-70b-instruct.pkl", "stored"),
    C("tab:current_channel", "llama.sat", 64.06,
      "pkls/current_channel/texas_hop1_noanon_noguide_llama-3.3-70b-instruct.pkl",
      f"{HOME}/texas_hop1_noanon_noguide_llama-3.3-70b-instruct.pkl", "stored"),
    C("tab:current_channel", "llama.taptn", 87.11,
      "pkls/current_channel/texas_hop1_noanon_guide_llama-3.3-70b-instruct.pkl",
      f"{HOME}/texas_hop1_noanon_guide_llama-3.3-70b-instruct.pkl", "stored"),

    C("tab:current_channel", "gemma.ego", 71.88,
      "pkls/current_channel/texas_ego_noguide_gemma-4-31b-it.pkl",
      f"{HOME}/texas_ego_noguide_gemma-4-31b-it.pkl", "stored"),
    C("tab:current_channel", "gemma.anon", 92.19,
      "pkls/current_channel/texas_hop1_anon_noguide_gemma-4-31b-it.pkl",
      f"{HOME}/texas_hop1_anon_noguide_gemma-4-31b-it.pkl", "stored"),
    C("tab:current_channel", "gemma.sat", 95.70,
      "pkls/current_channel/texas_hop1_noanon_noguide_gemma-4-31b-it.pkl",
      f"{HOME}/texas_hop1_noanon_noguide_gemma-4-31b-it.pkl", "stored"),
    C("tab:current_channel", "gemma.taptn", 96.48,
      "pkls/current_channel/texas_hop1_noanon_guide_gemma-4-31b-it.pkl",
      f"{HOME}/texas_hop1_noanon_guide_gemma-4-31b-it.pkl", "stored"),

    C("tab:current_channel", "qwen.ego", 68.75,
      "pkls/current_channel/texas_ego_noguide_qwen3.5-27b.pkl",
      f"{HOME}/texas_ego_noguide_qwen3.5-27b.pkl", "stored"),
    C("tab:current_channel", "qwen.anon", 69.92,
      "pkls/current_channel/texas_hop1_anon_noguide_qwen3.5-27b.pkl",
      f"{HOME}/texas_hop1_anon_noguide_qwen3.5-27b.pkl", "stored"),
    C("tab:current_channel", "qwen.sat", 92.19,
      "pkls/current_channel/texas_hop1_noanon_noguide_qwen3.5-27b.pkl",
      f"{HOME}/texas_hop1_noanon_noguide_qwen3.5-27b.pkl", "stored"),
    C("tab:current_channel", "qwen.taptn", 94.92,
      "pkls/current_channel/texas_hop1_noanon_guide_qwen3.5-27b.pkl",
      f"{HOME}/texas_hop1_noanon_guide_qwen3.5-27b.pkl.keyshift_bak", "stored",
      note="Paper uses the pre-keyshift snapshot (94.92). The later file in the home repo is 96.09."),

    C("tab:current_channel", "glm.ego", 83.59,
      "pkls/current_channel/texas_ego_noguide_glm-5.1.pkl",
      f"{HOME}/texas_ego_noguide_glm-5.1.pkl", "stored"),
    C("tab:current_channel", "glm.anon", 92.97,
      "pkls/current_channel/texas_hop1_anon_noguide_glm-5.1.pkl",
      f"{HOME}/texas_hop1_anon_noguide_glm-5.1.pkl", "stored"),
    C("tab:current_channel", "glm.sat", 94.53,
      "pkls/current_channel/texas_hop1_noanon_noguide_glm-5.1.pkl",
      f"{HOME}/texas_hop1_noanon_noguide_glm-5.1.pkl", "stored"),
    C("tab:current_channel", "glm.taptn", 96.09,
      "pkls/current_channel/texas_hop1_noanon_guide_glm-5.1.pkl",
      f"{HOME}/texas_hop1_noanon_guide_glm-5.1.pkl", "stored"),

    # ── tab:current_taptn ────────────────────────────────────────────────
    C("tab:current_taptn", "texas.gemma.gicl", 96.09,
      "pkls/current_taptn/texas_hop2_noanon_noguide_gemma-4-31b-it.pkl",
      f"{HOME}/texas_hop2_noanon_noguide_gemma-4-31b-it.pkl", "stored"),
    C("tab:current_taptn", "texas.gemma.taptn", 97.66,
      "pkls/current_taptn/texas_hop1_noanon_guide_gemma-4-31b-it_iter2_2hop.pkl",
      f"{HOME}/texas_hop1_noanon_guide_gemma-4-31b-it_iter2_2hop.pkl", "stored"),
    C("tab:current_taptn", "texas.qwen.gicl", 91.80,
      "pkls/current_taptn/texas_hop2_noanon_noguide_qwen3.5-27b.pkl",
      f"{HOME}/texas_hop2_noanon_noguide_qwen3.5-27b.pkl", "stored"),
    C("tab:current_taptn", "texas.qwen.taptn", 97.66,
      "pkls/current_taptn/texas_hop1_noanon_guide_qwen3.5-27b_iter2_2hop.pkl",
      f"{HOME}/texas_hop1_noanon_guide_qwen3.5-27b_iter2_2hop.pkl", "stored"),
    C("tab:current_taptn", "texas.glm.gicl", 94.92,
      "pkls/current_taptn/texas_hop2_noanon_noguide_glm-5.1.pkl",
      f"{HOME}/texas_hop2_noanon_noguide_glm-5.1.pkl", "stored"),
    C("tab:current_taptn", "texas.glm.taptn", 96.88,
      "pkls/current_taptn/texas_hop1_noanon_guide_glm-5.1_iter2_v2_2hop.pkl",
      f"{HOME}/texas_hop1_noanon_guide_glm-5.1_iter2_v2_2hop.pkl", "stored"),

    C("tab:current_taptn", "cora.gemma.gicl", 78.04,
      "pkls/current_taptn/cora_hop2_noanon_noguide_gemma-4-31b-it_reextract.pkl",
      f"{HOME}/cora_hop2_noanon_noguide_gemma-4-31b-it_reextract.pkl", "reextract"),
    C("tab:current_taptn", "cora.gemma.taptn", 79.52,
      "pkls/current_taptn/cora_2hop_gated_gemma-4-31b-it.pkl",
      f"{HOME}/cora_2hop_gated_gemma-4-31b-it.pkl", "acc_gate"),
    C("tab:current_taptn", "cora.qwen.gicl", 78.97,
      "pkls/current_taptn/cora_hop2_noanon_noguide_qwen3.5-27b_reextract.pkl",
      f"{HOME}/cora_hop2_noanon_noguide_qwen3.5-27b_reextract.pkl", "reextract"),
    C("tab:current_taptn", "cora.qwen.taptn", 80.07,
      "pkls/current_taptn/cora_2hop_gated_qwen3.5-27b.pkl",
      f"{HOME}/cora_2hop_gated_qwen3.5-27b.pkl", "acc_gate"),
    C("tab:current_taptn", "cora.glm.gicl", 77.49,
      "pkls/current_taptn/cora_hop2_noanon_noguide_glm-5.1_reextract.pkl",
      f"{HOME}/cora_hop2_noanon_noguide_glm-5.1_reextract.pkl", "reextract"),
    C("tab:current_taptn", "cora.glm.taptn", 81.00,
      "pkls/current_taptn/cora_2hop_gated_glm-5.1.pkl",
      f"{HOME}/cora_2hop_gated_glm-5.1.pkl", "acc_gate"),
]


# Extra artifacts copied for live / gate recompute / cost (not a table cell).
EXTRA_COPY = [
    (f"{HOME}/cost_probe/results.json", "cost_probe/results.json"),
    (f"{HOME}/cost_probe/cost_summary.json", "cost_probe/cost_summary.json"),
    (f"{HOME}/cost_probe/dense_graphicl/dense_input_tokens.json",
     "cost_probe/dense_graphicl/dense_input_tokens.json"),
    (f"{HOME}/cora_hop1_noanon_intv-era_gemma-4-31b-it_s2era_on_era.pkl",
     "pkls/current_taptn/gate_sources/cora_hop1_noanon_intv-era_gemma-4-31b-it_s2era_on_era.pkl"),
    (f"{HOME}/cora_hop1_noanon_gemma-4-31b-it_2hop_fc_v1v0_s2.pkl",
     "pkls/current_taptn/gate_sources/cora_hop1_noanon_gemma-4-31b-it_2hop_fc_v1v0_s2.pkl"),
    (f"{HOME}/cora_neighbors_eraS1_gemma-4-31b-it_s2.pkl",
     "pkls/current_taptn/gate_sources/cora_neighbors_eraS1_gemma-4-31b-it_s2.pkl"),
    (f"{HOME}/cora_hop1_noanon_noguide_glm-5.1_s2era_on_base_wr.pkl",
     "pkls/current_taptn/gate_sources/cora_hop1_noanon_noguide_glm-5.1_s2era_on_base_wr.pkl"),
    (f"{HOME}/cora_hop1_noanon_glm-5.1_2hop_fc_v0v1X_s2.pkl",
     "pkls/current_taptn/gate_sources/cora_hop1_noanon_glm-5.1_2hop_fc_v0v1X_s2.pkl"),
    (f"{HOME}/cora_neighbors_noguideS1_glm-5.1_s2.pkl",
     "pkls/current_taptn/gate_sources/cora_neighbors_noguideS1_glm-5.1_s2.pkl"),
    (f"{HOME}/cora_hop1_noanon_noguide_qwen3.5-27b_s2era_on_base_wr.pkl",
     "pkls/current_taptn/gate_sources/cora_hop1_noanon_noguide_qwen3.5-27b_s2era_on_base_wr.pkl"),
    (f"{HOME}/cora_hop1_noanon_qwen3.5-27b_2hop_part_v1_s2.pkl",
     "pkls/current_taptn/gate_sources/cora_hop1_noanon_qwen3.5-27b_2hop_part_v1_s2.pkl"),
    (f"{HOME}/cora_neighbors_noguideS1_qwen3.5-27b_s2.pkl",
     "pkls/current_taptn/gate_sources/cora_neighbors_noguideS1_qwen3.5-27b_s2.pkl"),
]


def unique_copies():
    seen = {}
    for c in CELLS:
        if c["src"] and c["dest"]:
            seen[c["dest"]] = c["src"]
    for src, dest in EXTRA_COPY:
        seen[dest] = src
    return seen


def cells_for(table: str):
    if table == "all":
        return list(CELLS)
    return [c for c in CELLS if c["table"] == table]
